services:
  web:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: luxury-shop_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: luxury-shop_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    image: redis:7
    container_name: luxury-shop_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  postgres_data:
  redis_data:
